VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "OutputWriter"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Public Sub writeLineArr(line() As String)
End Sub

Public Sub writeLine(ParamArray params() As Variant)
End Sub

Public Function getRowNum() As Long
End Function

Public Sub done()
End Sub
